apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: api
spec:
 template:
  spec:
    containers:
    - image: ko://github.com/imjasonh/tekless/cmd/server
      args:
      - --watcher_image
      - ko://github.com/imjasonh/tekless/cmd/watcher
      - --host
      - https://api-zrxvguzx2q-uk.a.run.app
    timeoutSeconds: 20
